package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"golang.org/x/net/context"
)

// FindTodosHandlerFunc turns a function with the right signature into a find todos handler
type FindTodosHandlerFunc func(FindTodosParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindTodosHandlerFunc) Handle(params FindTodosParams) middleware.Responder {
	return fn(params)
}

// FindTodosHandler interface for that can handle valid find todos params
type FindTodosHandler interface {
	Handle(FindTodosParams) middleware.Responder
}

// NewFindTodos creates a new http.Handler for the find todos operation
func NewFindTodos(ctx *middleware.ApiContext, handler FindTodosHandler) *FindTodos {
	return &FindTodos{Context: ctx, Handler: handler}
}

/*FindTodos swagger:route GET / todos findTodos

FindTodos find todos API

*/
type FindTodos struct {
	Context *middleware.ApiContext
	Params  FindTodosParams
	Handler FindTodosHandler
}

func (o *FindTodos) ServeHTTP(ctx context.Context, rw http.ResponseWriter, r *http.Request) {
	route := middleware.MatchedRouteFromContext(ctx)
	o.Params = NewFindTodosParams()

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(ctx, rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(o.Params) // actually handle the request

	o.Context.Respond(ctx, rw, r, route.Produces, route, res)

}
